name: Export

on:
  push:
    paths:
    - '**.kicad_sch'
    - '**.kicad_pcb'
    - '**.round-tracks-config'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.round-tracks-config'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        # Required - kibot config file
        config: config.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: 'pcb-esp32-tmc2209.kicad_sch'
        # optional - PCB design file
        board: 'pcb-esp32-tmc2209.kicad_pcb'
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output